### ISSUE TITLE
testing bucky

### ISSUE THREAD

**Issue by bucky2076** [funtastix/rinnaitouch#20]
Going to use this issue to facilitate testing...
Still not getting very far when installing... sorry to say.
Please let me know if there is an easy way to update the component after a fix.

Currently getting unexpected error... as below.

- I ssh into HA, and renamed the custom_component, and then did a git clone of the latest from master.
- rea-dded the  integration, and seemed to work initially.
- Prompted for zones and hostname, I ticked zonea and b.
- Integration page did show initially, but entities not accessible.
- The name of the integration was rinnai touch zoneb. Should have been just rinnai touch.
- Subsequent attempts to delete/readd resulted in the error below. I can't seem to get around this no matter how many times I re-add/reboot.

2022-03-09 08:18:33 ERROR (MainThread) [custom_components.rinnaitouch.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/rinnaitouch/pyrinnaitouch/system.py", line 615, in ConnectToTouch
client.connect((touchIP, port))
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/rinnaitouch/pyrinnaitouch/system.py", line 535, in renewConnection
self._client = await self.ConnectToTouch(self._touchIP,self._touchPort)
File "/config/custom_components/rinnaitouch/pyrinnaitouch/system.py", line 617, in ConnectToTouch
except ConnectionRefusedError(err):
NameError: name 'err' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/rinnaitouch/config_flow.py", line 49, in async_step_user
status = await system.GetStatus()
File "/config/custom_components/rinnaitouch/pyrinnaitouch/system.py", line 577, in GetStatus
if await self.renewConnection():
File "/config/custom_components/rinnaitouch/pyrinnaitouch/system.py", line 538, in renewConnection
except ConnectionRefusedError(err):
UnboundLocalError: local variable 'err' referenced before assignment

**Comment by funtastix** [comment]
Do you have the original logs before it failed? I don't have zones, so I assume something goes wrong parsing the zone data. Then the connection is killed (which I can probably do more safely) and upon reconnection the device misbehaves and needs to be restarted (or you can restart your router) before it let's you connect again (or wait a long time, between 10 and 24 hours).

**Comment by bucky2076** [comment]
I did manage to add the integration after working in the garden and leaving it alone for a while.
The entity is still unavailable and after a restart cannot load correctly....
![image](https://user-images.githubusercontent.com/6071511/157388847-534fda2f-9364-4b8b-a38d-906592221fb7.png)

**Comment by funtastix** [comment]
this should now be fixed on develop. I will also release this improvement as 0.6.2

**Comment by bucky2076** [comment]
getting a bit further... I can install ok, but the entities are unavailable.... so not much I can do. 
Log is not particularly helpful... either.
how do I turn on debug ?

**Comment by bucky2076** [comment]
here is the debug log after deleteing and re-adding the integration.
2022-03-10 06:32:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Creating new client...
2022-03-10 06:32:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Error during renewConnection timed out
2022-03-10 06:32:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] renewing connection failed, not sending command
2022-03-10 06:32:26 DEBUG (MainThread) [custom_components.rinnaitouch] Get controller with IP: 192.168.92.60
2022-03-10 06:32:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Creating new client...
2022-03-10 06:32:36 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Error during renewConnection timed out
2022-03-10 06:32:36 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] renewing connection failed, not sending command
2022-03-10 06:32:36 INFO (MainThread) [custom_components.rinnaitouch.climate] Set up RinnaiTouch entity 192.168.92.60
2022-03-10 06:32:36 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 06:32:36 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Set up RinnaiTouch zone A entity 192.168.92.60
2022-03-10 06:32:36 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Set up RinnaiTouch zone B entity 192.168.92.60

**Comment by bucky2076** [comment]
I made a couple of changes and got some improvement.
I deleted the previous integration for homekit, and also permanatly stopped the homekit controller docker... so it can't complete for connectivity.
I also deleted previous integrations...
Finally I recycled the wifi touch module, and got some connectivity.

'
![image](https://user-images.githubusercontent.com/6071511/157600799-0da90327-6e19-463b-b107-2ef80fe7f76b.png)

I would like to zip up the log and send it to you... but not sure how to do that... hmmmm

Here is a snippet. Notice there are some JSON errors...

49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36032), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:41:00 ERROR (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (AttributeError("'NoneType' object has no attribute 'group'"))
2022-03-10 16:41:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:41:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:41:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:41:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36032), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:42:00 ERROR (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (AttributeError("'NoneType' object has no attribute 'group'"))
2022-03-10 16:42:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:42:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:42:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:42:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36032), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:43:00 ERROR (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (AttributeError("'NoneType' object has no attribute 'group'"))
2022-03-10 16:43:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:43:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:43:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:43:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36032), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:44:00 ERROR (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (AttributeError("'NoneType' object has no attribute 'group'"))
2022-03-10 16:44:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:44:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:44:00 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:44:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Creating new client...
2022-03-10 16:44:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36262), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "THU", "TM": "16:44", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"HGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "Y", "PS": "Y", "DG": "A" }, "OOP": {"ST": "N", "CF": "Y", "FL": "00", "SN": "N" }, "GSO": {"OP": "A", "SP": "20", "AO": "N" }, "GSS": {"HC": "N", "FS": "Y", "GV": "N", "PH": "N", "AT": "R", "AZ": "R" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "Y" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "221" }, "ZAS": {"AE": "N", "MT": "221" }, "ZBS": {"AE": "N", "MT": "221" }, "ZCS": {"AE": "N", "MT": "221" }, "ZDS": {"AE": "N", "MT": "221" } } }]
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heater is ON
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Fan Speed is: 00
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat OpMode is: A
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat set temp is: 20
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in HEAT mode
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:44:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:44:53 ERROR (MainThread) [homeassistant.components.shelly] Timeout fetching apartment-switch data
2022-03-10 16:45:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36262), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "THU", "TM": "16:45", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"HGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "Y", "PS": "Y", "DG": "A" }, "OOP": {"ST": "N", "CF": "Y", "FL": "00", "SN": "N" }, "GSO": {"OP": "A", "SP": "20", "AO": "N" }, "GSS": {"HC": "N", "FS": "Y", "GV": "N", "PH": "N", "AT": "R", "AZ": "R" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "Y" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "221" }, "ZAS": {"AE": "N", "MT": "221" }, "ZBS": {"AE": "N", "MT": "221" }, "ZCS": {"AE": "N", "MT": "221" }, "ZDS": {"AE": "N", "MT": "221" } } }]
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heater is ON
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Fan Speed is: 00
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat OpMode is: A
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat set temp is: 20
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in HEAT mode
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 221
2022-03-10 16:45:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:46:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36262), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "THU", "TM": "16:46", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"HGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "Y", "PS": "Y", "DG": "A" }, "OOP": {"ST": "N", "CF": "Y", "FL": "00", "SN": "N" }, "GSO": {"OP": "A", "SP": "20", "AO": "N" }, "GSS": {"HC": "N", "FS": "Y", "GV": "N", "PH": "N", "AT": "R", "AZ": "R" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "Y" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "222" }, "ZAS": {"AE": "N", "MT": "222" }, "ZBS": {"AE": "N", "MT": "222" }, "ZCS": {"AE": "N", "MT": "222" }, "ZDS": {"AE": "N", "MT": "222" } } }]
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heater is ON
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Fan Speed is: 00
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat OpMode is: A
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat set temp is: 20
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in HEAT mode
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 222
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 222
2022-03-10 16:46:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:47:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36262), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "THU", "TM": "16:47", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"HGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "Y", "PS": "Y", "DG": "A" }, "OOP": {"ST": "N", "CF": "Y", "FL": "00", "SN": "N" }, "GSO": {"OP": "A", "SP": "20", "AO": "N" }, "GSS": {"HC": "N", "FS": "Y", "GV": "N", "PH": "N", "AT": "R", "AZ": "R" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "Y" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "222" }, "ZAS": {"AE": "N", "MT": "222" }, "ZBS": {"AE": "N", "MT": "222" }, "ZCS": {"AE": "N", "MT": "222" }, "ZDS": {"AE": "N", "MT": "222" } } }]
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heater is ON
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Fan Speed is: 00
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat OpMode is: A
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heat set temp is: 20
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in HEAT mode
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 222
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 222
2022-03-10 16:47:53 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-10 16:48:49 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.92.250', 36262), raddr=('192.168.92.60', 27847)> / False
2022-03-10 16:48:53 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV

**Comment by funtastix** [comment]
This looks quite good and normal. The JSON debug errors are due to the unit shutting the connection from its side which eventually the integration detects and reconnects. I'm still trying to improve it in the future by regularly sending an empty command (like the homekit integration) but haven't figured out a good way yet.

**Comment by bucky2076** [comment]
oh good. I will do more testing tomorrow... In the meantime I backed out your integration as my system is a little unstable. Going to get it to a better place.

The wifi unit is finicky with respect to connectivity and keep alive... so good luck with that.

**Comment by funtastix** [comment]
I think I've worked it out. the latest 0.6.3 release keeps connectivity really well.

**Comment by funtastix** [comment]
Finally added the fan control, and also managed to resolve the connectivity issues. In the same process I made the whole thing much more responsive, too.

**Comment by bucky2076** [comment]
thanks bud. Will give it a crack shortly. Been getting supervisor errors, which i now found are unrelated. But working on getting my installation a little more stable.

**Comment by bucky2076** [comment]
it may be good for you to know... that I have 2 x zones A & B. They do not have separate thermostats... 
I have a central thermostat  unit (NC7). This unit controls both zones. They are not independent. The zones are either on or off.

**Comment by funtastix** [comment]
That's an interesting setup. How does the Rinnai Touch App deal with that? If you use the integration, what happens if you turn a zone on or off?

I've added a new feature on develop that allows temp sensors in each zone (external).

**Comment by bucky2076** [comment]
I think that is the difference between what they call mtsp and stsp setups. mtsp has a senosr for each zone and each zone is individually controlled. stsp implies a single temp senosr for all zones, and all you can do is turn a zone on or off to effect air flow to a zone. My zone A has most of the living areas and is always on. zone b controls outer reaches which i turn on only if kids are home.
The app shows a button for each zone, which i can flick on or off. So a switch is all that is needed for each zone.

**Comment by funtastix** [comment]
The integration provides a simple switch for each zone already. Have you tried them? I.e. each zone comes with a climate entity, but also with a simple on/off switch, an auto switch (for MTSP), a temp sensor, and a target temp sensor (mainly for MTSP).

**Comment by bucky2076** [comment]
thanks for this. I can't seem to add the integration back in... now that I've stabilised my system. Did something change ?
I ssh'ed into the system and cloned from git. But won't show up in the integration page when i search. ?

**Comment by funtastix** [comment]
I've noticed this before, after installation and restart, also with other integrations. There's a cache in the browser and a hard refresh of the page can be necessary.

I have made a fair few changes in terms of refactoring. I've moved out the library that controls the unit and uploaded that into PyPi. Currently, I'm cleaning the code and improving lint scores before then moving things around to make it HACS compatible .

**Comment by bucky2076** [comment]
working a lot better for me now... will make some comments after a bit more testing. Well done.

**Comment by bucky2076** [comment]
Config flow could not be loaded: undefined
I am now getting the above error, when trying to re-add the integration. Tried deleting, rebooting, re-adding. But not working.

**Comment by funtastix** [comment]
Is that the latest develop? 0.7.2 on master is the last stable version

**Comment by reesion** [comment]
Hi, I am having the same issue with the latest release as well.

2022-03-13 19:37:14 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration rinnaitouch - received exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
req = REQUIREMENT.parseString(requirement_string)
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
raise exc
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
loc, tokens = self._parse( instring, 0 )
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
loc, exprtokens = e._parse( instring, loc, doActions )
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 13), (line:1, col:14)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/package.py", line 38, in is_installed
pkg_resources.get_distribution(package)
File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 475, in get_distribution
dist = Requirement.parse(dist)
File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3134, in parse
req, = parse_requirements(s)
File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3089, in __init__
super(Requirement, self).__init__(requirement_string)
File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'=0.7.2'": Expected stringEnd
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 79, in async_setup_component
return await task
File "/usr/src/homeassistant/homeassistant/setup.py", line 182, in _async_setup_component
await async_process_deps_reqs(hass, config, integration)
File "/usr/src/homeassistant/homeassistant/setup.py", line 360, in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
await _async_process_integration(hass, integration, done)
File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in _async_process_integration
await async_process_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 162, in async_process_requirements
await _async_process_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_requirements
if pkg_util.is_installed(req):
File "/usr/src/homeassistant/homeassistant/util/package.py", line 45, in is_installed
req = pkg_resources.Requirement.parse(urlparse(package).fragment)
File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3134, in parse
req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)

**Comment by funtastix** [comment]
Fix is now on master: https://github.com/funtastix/rinnaitouch/releases/tag/0.8.0 and latest develop

**Comment by funtastix** [comment]
I've now made the integration HACS compatible.

**Comment by bucky2076** [comment]
hacs is most welcome... thank you. I'm doing another test and here are some comments ... Firstly I can see you are making great progress... kudos.

- Main Temp sensor - showing as unavailable.
- When you make a change, takes 1 min to show... is this because it waits for a refresh ?
- can you consolidate all the zone info inside a respective climate entitiy. Attribs supported will be site dependent. My zones simply have an on/off but others may have indpendent temp sensors. This may make things a little clearer...
- Advance button presumably moves you to the next schedule time. Is there any way to show you are in manual mode? If you are in schedule mode, is there any way to show what period you are in ?
- i am still unclear about the preset button. What does it do ?
- more observations to come...
-

**Comment by funtastix** [comment]
> Main Temp sensor - showing as unavailable.
- Have you got a NC-7 controller? Otherwise it won't report anything and will be unavailable.
> When you make a change, takes 1 min to show... is this because it waits for a refresh ?
- for me it takes a few seconds, often almost instantly now. Refreshes are now every 5-10 secs. Are you on 0.9.0?
> can you consolidate all the zone info inside a respective climate entity
- I have, but I'm doing it blindly, as I don't have zones. Can you take a screenshot of what entities you have for your zones? There should be a few: temperature sensor, climate, zone on/off switch.
> Advance button presumably moves you to the next schedule time. 
- correct
> Is there any way to show you are in manual mode?
- there is. There is a switch auto/manual, but also the climate control will show it. See some of the screen shots in the new wiki page
> If you are in schedule mode, is there any way to show what period you are in ?
- I have not looked I to that. There could be, but that's complex. What would you expect to see in terms of info? The current settings?
> i am still unclear about the preset button. What does it do ?
- it's shouldn't be a button but a select. Use an entity card with it and you get a dropdown to change the preset, so one of heat, cool, evap (depending on you unit)

**Comment by funtastix** [comment]
Looks like it's actually not that complex with the advance. Should just be two sensors:

AT -- Schedule operating mode time period (Wake, Leave, Return, Pre-Sleep, Sleep)
AZ -- Schedule time period advanced to (Wake, Leave, Return, Pre-Sleep, Sleep)

**Comment by bucky2076** [comment]
yes, I have an nc7. I bought and installed myself just recently.
below are pics of the 27 entities that are added. I find the zone stuff a little confusing, and wonder if what I'm seeing is by design.
![rinna1](https://user-images.githubusercontent.com/6071511/158113164-f4da3235-4548-420c-8236-56dc74050fdb.png)
![rinna2](https://user-images.githubusercontent.com/6071511/158113177-5fee6f15-d3e5-40dc-8394-a73d9c059119.png)

with respect to preset... I only have heat, so only 1 item showing ... which is ok.

I am going to delete and re-add via hacs... nice work so far.

**Comment by funtastix** [comment]
Looks pretty good. I find the zone stuff a bit hard to get my head around without having a system that I can play with. Would love to see the logs (JSON) with the zone put into heating mode. I might be able to mock this to work on it better. Should also give me an idea why it wouldn't read the temperature from the NC-7.

The entities for each zone are to control the zones, but not all zone setups support all features, and it may depend on STSP vs MTSP what you can do. You can use the entities as they apply to you in lovelace, so it's flexible and should support most systems out there. I'll be adding some documentation over the next few days/weeks. Happy to get contributions from "zoners"

**Comment by funtastix** [comment]
> Looks like it's actually not that complex with the advance. Should just be two sensors:
> 
> AT -- Schedule operating mode time period (Wake, Leave, Return, Pre-Sleep, Sleep) AZ -- Schedule time period advanced to (Wake, Leave, Return, Pre-Sleep, Sleep)

I've implemented this now for the main controller. Zones to follow, but I assume that has time as it only applies to MTSP systems. I had the advance functionality figured a bit incorrectly, so this really helped clear that up. Now you can advance, and then cancel advance on the next button press. The sensors (and the button icon) indicate the state.

**Comment by bucky2076** [comment]
not quite working yet for me. Here is my testbed... actual temp not working, and advance sensor not showing.
![image](https://user-images.githubusercontent.com/6071511/158264677-910da696-38f1-4fd2-a8ba-0c5d1efefb6b.png)

**Comment by funtastix** [comment]
This is pretty helpful. I've committed what I hope to be a fix to develop. you may be able to just pull the file "sensor.py" from there and overwrite it to test. I can see the temp is correctly picked up in the climate entity (Currently), I just had some problems in the availability which was a stupid mistake.

The advance sensor seems to work as designed. There are 2 sensors, one with the currently schedule period, one with the advance one. It only returns a period once the button has been pressed and displays the temporary new period. The icon on the button would then change.

**Comment by bucky2076** [comment]
do you mind committing to master ? Easier for me to update from hacs... many thanks.

**Comment by funtastix** [comment]
Done

**Comment by bucky2076** [comment]
nothing really chnaged for me... I did a re-download via hacs... version seems to be 0.91

2022-03-15 17:21:01 DEBUG (MainThread) [pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "TUE", "TM": "17:20", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"HGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "Y", "PS": "Y", "DG": "A" }, "OOP": {"ST": "N", "CF": "Y", "FL": "00", "SN": "N" }, "GSO": {"OP": "M", "SP": "24", "AO": "N" }, "GSS": {"HC": "Y", "FS": "Y", "GV": "Y", "PH": "N", "AT": "W", "AZ": "R" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "Y" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "230" }, "ZAS": {"AE": "Y", "MT": "230" }, "ZBS": {"AE": "Y", "MT": "230" }, "ZCS": {"AE": "N", "MT": "230" }, "ZDS": {"AE": "N", "MT": "230" } } }]
2022-03-15 17:21:01 DEBUG (MainThread) [pyrinnaitouch.heater] Heater is ON
2022-03-15 17:21:01 DEBUG (MainThread) [pyrinnaitouch.heater] Fan Speed is: 00
2022-03-15 17:21:01 DEBUG (MainThread) [pyrinnaitouch.heater] Heat OpMode is: M
2022-03-15 17:21:01 DEBUG (MainThread) [pyrinnaitouch.heater] Heat set temp is: 24
2022-03-15 17:21:01 DEBUG (MainThread) [pyrinnaitouch.system] We are in HEAT mode
2022-03-15 17:21:01 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 230
2022-03-15 17:21:01 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True
2022-03-15 17:21:01 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: None
2022-03-15 17:21:01 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 230
2022-03-15 17:21:01 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor should be reported: True

**Comment by funtastix** [comment]
Did you restart? As you can see it reads the internal sensor and determines it should use it. The problem was with availability of the sensor.

**Comment by bucky2076** [comment]
umm yes I did restart after ... but no change to the sensor....
![image](https://user-images.githubusercontent.com/6071511/158319769-7ff65bcb-8ac4-49e6-9129-2db56be5cb93.png)

gonna reboot the whole server.

**Comment by bucky2076** [comment]
I don't think its bubbling up correctly to the temp sensor. Showing as unavailable.

**Comment by funtastix** [comment]
I'll have another look at it

**Comment by funtastix** [comment]
I've changed the implementation fundamentally, committed to master. Can you give it another try?

**Comment by funtastix** [comment]
I've built a little mocker script to be able to test with your configuration (this will help me a lot going forward!). With master it works for me and the sensor is alive and reports 24.0C.

I've pushed this to release 0.9.2, maybe it's just a HACS thing.

To be sure, you can check the sensor.py file in the directory, it should have loads of code commented out in the temperature sensor section.

**Comment by bucky2076** [comment]
temp sensor is coming through... thanks. pushing to 0.92 seemed to do the trick. cool.

note, the period still not showing... not sure why... but not a biggie.
I was going to offer you the ability to dial in to diagnose... but perhaps not really needed.

well done.

![image](https://user-images.githubusercontent.com/6071511/158513028-9b9f3af4-ce92-491a-b55c-f82824e13b48.png)

**Comment by funtastix** [comment]
That's great.

Please note, period won't come through unless you are in Auto mode (you are in Heat/cool which maps to manual mode on the unit). The sensor on your UI is the advance sensor, so it'll still be N/A unless you press the advance button. There is a second sensor (time period) that will display the current period.

**Comment by funtastix** [comment]
Closing due to inactivity. All my testing seems to show it's now working as I had originally intended. Happy to re-open or open a new issue from here.
